version: '3.6'

services:
  data-hub-schematron-example:
      image: marklogicdb/marklogic-db:latest-11
      container_name: data-hub-schematron-example
      domainname: .
      environment:
        - MARKLOGIC_INIT=true
        - MARKLOGIC_ADMIN_USERNAME=admin
        - MARKLOGIC_ADMIN_PASSWORD=admin
        - TZ=UTC
      ports:
        - 7997-8013:7997-8013
      networks:
        - external_net
        - internal_net
      volumes:
        - 'marklogic:/var/opt/MarkLogic'
        - './data:/mnt/data'      
volumes:
  marklogic:
networks:
  external_net: {}
  internal_net:
    internal: true